# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-03 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column=b'title', max_length=30)),
                ('content', models.TextField(db_column=b'content')),
            ],
            options={
                'db_table': 'faq',
                'verbose_name_plural': 'Faq',
            },
        ),
    ]
