# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-29 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='nickname', max_length=200)),
                ('review_row', models.TextField()),
                ('stars_support', models.TextField()),
                ('stars_speed', models.TextField()),
                ('stars_experience', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
