# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-29 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='stars_experience',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='stars_speed',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='stars_support',
        ),
    ]
