# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-29 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20171029_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='stars_experience',
            field=models.CharField(default='5', max_length=100),
        ),
        migrations.AddField(
            model_name='reviews',
            name='stars_speed',
            field=models.CharField(default='5', max_length=100),
        ),
        migrations.AddField(
            model_name='reviews',
            name='stars_support',
            field=models.CharField(default='5', max_length=100),
        ),
    ]
